#lang pollen

◊(define-meta title "For Kindle: The 33 Best Science Fiction Novels Ever")
◊(define-meta published "2011-09-14")
◊(define-meta topics "Reddit,Kindle,ebooks")

Another “best of” list for your Kindle, brought to you this time by ◊link["http://www.reddit.com/r/AskReddit/comments/k70dh/whats_the_best_scifi_novel_you_have_ever_read/"]{this Ask Reddit post}.

The links given in this list are to Kindle editions of the books, free wherever possible, unless there have been severe quality complaints with the ebook versions. If you want to see book covers and a summary of comments by those who have read them, see this ◊link["http://blamcast.net/articles/best-science-fiction-books"]{summary of the reddit thread by John Forsythe}.

◊ol{
◊item{◊emph{◊amazon["B001F0WXY0"]{Dune}} by Frank Herbert — 1965}
◊item{◊emph{◊amazon["B0043M4ZH0"]{The Hitchhiker’s Guide To The Galaxy}} by Douglas Adams — 1979
Good light bathroom reading. Perhaps the schtick will wear off as quickly for you as it did for me, but lots of people never tire of it.}
◊item{◊emph{◊amazon["B003G4W49C"]{Ender’s Game}} by Orson Scott Card — 1985
My personal favourite of the ones on this list that I have read.}
◊item{◊emph{◊amazon["B000FC1PWA"]{Foundation Trilogy}} by Isaac Asimov — 1942
More of a saga broken up into smaller novels with one majestic overarching connection. I really enjoyed this one.}
◊item{◊emph{◊amazon["B004G60EHS"]{Hyperion}} by Dan Simmons — 1989
“On the eve of Armageddon, with the entire galaxy at war, seven pilgrims set forth on a final voyage to Hyperion seeking the answers to the unsolved riddles of their lives.”}
◊item{◊emph{◊amazon["B000O76ON6"]{Neuromancer}} by William Gibson — 1984
“Case was the hottest computer cowboy cruising the information superhighway — jacking his consciousness into cyberspace, soaring through tactile lattices of data and logic, rustling encoded secrets for anyone with the money to buy his skills. Then he double-crossed the wrong people, who caught up with him in a big way — and burned the talent out of his brain, micron by micron. Banished from cyberspace, trapped in the meat of his physical body, Case courted death in the high-tech underworld. Until a shadowy conspiracy offered him a second chance — and a cure — for a price…”}
◊item{◊emph{◊amazon["B000FBJCJE"]{Snow Crash}} by Neil Stephenson — 1992
“In California of the near future, when the U.S. is only a ‘Burbclave’ (city-state), the Mafia is just another franchise chain, and there are no laws to speak of, Hiro Protagonist follows clues from the Bible, ancient Sumer and high technology to help thwart an attempt to take control of civilization — such as it is.”}
◊item{◊emph{◊amazon["B00AHGSVKS"]{Childhood’s End}} by Arthur C. Clark — 1953
“The Overlords appeared suddenly over every city — intellectually, technologically, and militarily superior to humankind. Benevolent, they made few demands: unify earth, eliminate poverty, and end war. With little rebellion, humankind agreed, and a golden age began. But at what cost? With the advent of peace, man ceases to strive for creative greatness, and a malaise settles over the human race. To those who resist, it becomes evident that the Overlords have an agenda of their own.”}
◊item{◊emph{◊amazon["B005BVM9YI"]{The Forever War}} by Joe Haldeman — 1974
◊emph{“Short, but fantastically well executed. It might be so good, in part, because it’s short.”} — “Humans first bumped heads with the Taurans when we began using collapsars to travel the stars. Although the collapsars provide nearly instantaneous travel across vast distances, the relativistic speeds associated with the process means that time passes slower for those aboard ship. For William Mandella, a physics student drafted as a soldier, that means more than 27 years will have passed between his first encounter with the Taurans and his homecoming, though he himself will have aged only a year. When Mandella finds that he can’t adjust to Earth after being gone so long from home, he reenlists, only to find himself shuttled endlessly from battle to battle as the centuries pass.”}
◊item{◊emph{◊amazon["B01513ZIL6"]{Ringworld}} by Larry Niven — 1970}
◊item{◊emph{◊amazon["B000SEGTI0"]{Do Androids Dream of Electric Sheep?}} by Philip K. Dick — 1968
This is the novel on which the movie ◊emph{Blade Runner} was based. “By 2021, the World War had killed millions, driving entire species into extinction and sending mankind off-planet. Those who remained coveted any living creature, and for people who couldn’t afford one, companies built incredibly realistic simulacrae: horses, birds, cats, sheep…they even built humans. Emigrées to Mars received androids so sophisticated it was impossible to tell them from true men or women. Fearful of the havoc these artificial humans could wreak, the government banned them from Earth. But when androids didn’t want to be identified, they just blended in.”}
◊item{◊emph{◊amazon["B000TO0TDK"]{A Stranger in a Strange Land}} by Robert A. Heinlein — 1961
“The story of Valentine Michael Smith, born during, and the only survivor of, the first manned mission to Mars. Michael is raised by Martians, and he arrives on Earth as a true innocent: he has never seen a woman and has no knowledge of Earth’s cultures or religions. But he brings turmoil with him, as he is the legal heir to an enormous financial empire, not to mention de facto owner of the planet Mars. With the irascible popular author Jubal Harshaw to protect him, Michael explores human morality and the meanings of love.”}
◊item{◊emph{◊amazon["B004EYTK2C"]{Starship Troopers}} by Robert A. Heinlein — 1987
“Juan Rico signed up with the Federal Service on a lark, but despite the hardships and rigorous training, he finds himself determined to make it as a cap trooper. In boot camp he will learn how to become a soldier, but when he graduates and war comes (as it always does for soldiers), he will learn why he is a soldier.”}
◊item{The ◊emph{Culture} Series by Iain M. Banks — 1987: ◊amazon["B0013TX6FI"]{Consider Phlebas}, ◊amazon["B0046A9NLC"]{Surface Detail}, ◊amazon["B0015DWLTE"]{Use of Weapons}, ◊amazon["B000VMHI98"]{Matter} and others}
◊item{◊emph{A Canticle For Leibowitz} by Walter M. Miller, Jr. — 1960 (Not currently available for Kindle)
Strangely arresting and thought-provoking look through the lens of a post-apocalyptic world.}
◊item{◊emph{◊amazon["B00AHIP8ZM"]{Rendezvous With Rama}} by Arthur C. Clarke — 1973}
◊item{◊emph{◊amazon["B000FC1AFC"]{Pandora’s Star}} by Peter F. Hamilton — 2004
“Hamilton creates a dense, thoroughly defined twenty-fourth-century world, in which humanity has colonized the stars, thanks to the discovery of wormhole travel, and established a successful commonwealth. The species has even encountered aliens and space-faring artifacts. One remaining mystery is the barrier around stars known as the Dyson Pair. Human curiosity still being what it is, a spaceship capable of faster-than-light travel (thanks to those wormholes again) goes to investigate. When what’s behind the barrier is discovered, the thrill-ride really starts. Aliens formerly trapped inside it, fighting over limited resources, are freed to invade human space.”}
◊item{◊emph{◊amazon["B004YDL2CY"]{The Mote In God’s Eye}} by Larry Niven and Jerry Pournelle — 1974
“In the year 3016, the Second Empire of Man spans hundreds of star systems, thanks to the faster-than-light Alderson Drive. No other intelligent beings have ever been encountered, not until a light sail probe enters a human system carrying a dead alien. The probe is traced to the Mote, an isolated star in a thick dust cloud, and an expedition is dispatched. In the Mote the humans find an ancient civilization — at least one million years old — that has always been bottled up in their cloistered solar system for lack of a star drive. The Moties are welcoming and kind, yet rather evasive about certain aspects of their society. It seems the Moties have a dark problem, one they’ve been unable to solve in over a million years.”}
◊item{◊emph{◊amazon["B0054LNIQS"]{The Stars My Destination}} by Alfred Bester — 1956
“Marooned in outer space after an attack on his ship, Nomad, Gulliver Foyle lives to obsessively pursue the crew of a rescue vessel that had intended to leave him to die.”}
◊item{◊emph{◊amazon["B000FBFMZ2"]{Altered Carbon}} by Richard K. Morgan — 2002
“In the 25th century, it’s difficult to die a final death. Humans are issued a cortical stack, implanted into their bodies, into which consciousness is “digitized” and from which — unless the stack is hopelessly damaged — their consciousness can be downloaded (“resleeved”) with its memory intact, into a new body. While the Vatican is trying to make resleeving (at least of Catholics) illegal, centuries-old aristocrat Laurens Bancroft brings Takeshi Kovacs (an Envoy, a specially trained soldier used to being resleeved and trained to soak up clues from new environments) to Earth, where Kovacs is resleeved into a cop’s body to investigate Bancroft’s first mysterious, stack-damaging death.”}
◊item{◊emph{◊amazon["B000QCS914"]{Red Mars}} by Kim Stanley Robinson — 1993
The first in a trilogy. “An action-packed and thoughtful tale of the exploration and settlement of Mars—riven by both personal and ideological conflicts—in the early 21st century.”}
◊item{◊emph{◊amazon["B01A6E8EQ6"]{2001: A Space Odyssey}} by Arthur C. Clarke — 1968
“When an enigmatic monolith is found buried on the moon, scientists are amazed to discover that it’s at least 3 million years old. Even more amazing, after it’s unearthed the artifact releases a powerful signal aimed at Saturn. What sort of alarm has been triggered? To find out, a manned spacecraft, the Discovery, is sent to investigate. Its crew is highly trained — the best — and they are assisted by a self-aware computer, the ultra-capable HAL 9000. But HAL’s programming has been patterned after the human mind a little too well. He is capable of guilt, neurosis, even murder, and he controls every single one of Discovery’s components. The crew must overthrow this digital psychotic if they hope to make their rendezvous with the entities that are responsible not just for the monolith, but maybe even for human civilization.”}
◊item{◊emph{Contact} by Carl Sagan — 1985 (Not currently available for Kindle)
“After years of scanning the galaxy for signs of somebody or something else, this team believes they’ve found a message from an intelligent source — and they travel deep into space to meet it.”}
◊item{◊emph{◊amazon["B003XREM5G"]{The Sirens Of Titan}} by Kurt Vonnegut, Jr. — 1959
“Plain and simple, there would probably be no Hitchhiker’s Guide to the Galaxy as we know it without The Sirens of Titan.”}
◊item{◊emph{◊amazon["B000FC1PW0"]{I, Robot}} by Isaac Asimov — 1950
“In ◊emph{I, Robot}, Asimov chronicles the development of the robot through a series of interlinked stories: from its primitive origins in the present to its ultimate perfection in the not-so-distant future—a future in which humanity itself may be rendered obsolete.”}
◊item{◊emph{◊amazon["B00YBA7PGW"]{The Left Hand Of Darkness}} by Ursula K. Le Guin — 1969
“Genly Ai is an emissary from the human galaxy to Winter, a lost, stray world. His mission is to bring the planet back into the fold of an evolving galactic civilization, but to do so he must bridge the gulf between his own culture and prejudices and those that he encounters. On a planet where people are of no gender — or both — this is a broad gulf indeed.”}
◊item{◊emph{◊amazon["B001QL5MAA"]{Revelation Space}} by Alastair Reynolds — 2000
“Sylveste is the only man ever to return alive and sane from a Shroud, an enclave in space protected by awesome gravity-warping defenses. Now an intuition he doesn’t understand makes him explore the dead world Resurgam, whose birdlike natives long ago tripped some booby trap that made their own sun erupt in a deadly flare. Meanwhile, the vast, decaying lightship Nostalgia for Infinity is coming for Sylveste, whose dead father (in AI simulation) could perhaps help the Captain, frozen near absolute zero yet still suffering monstrous transformation by nanotech plague. Most of Infinity’s tiny crew have hidden agendas — Khouri the reluctant contract assassin believes she must kill Sylveste to save humanity — and there are two bodiless stowaways, one no longer human and one never human. Shocking truths emerge from bluff, betrayal, and ingenious lies.”}
◊item{◊emph{◊amazon["B000SEIK2S"]{Old Man’s War}} by John Scalzi — 2005
“With his wife dead and buried, and life nearly over at 75, John Perry takes the only logical course of action left him: he joins the army. Now better known as the Colonial Defense Force (CDF), Perry’s service-of-choice has extended its reach into interstellar space to pave the way for human colonization of other planets while fending off marauding aliens. The CDF has a trick up its sleeve that makes enlistment especially enticing for seniors: the promise of restoring youth.”}
◊item{◊emph{◊amazon["B0015DPXKI"]{Anathem}} by Neal Stephenson — 2008
“Fraa Erasmas is a young avout living in the Concent of Saunt Edhar, a sanctuary for mathematicians, scientists, and philosophers, protected from the corrupting influences of the outside ‘saecular’ world by ancient stone, honored traditions, and complex rituals. Over the centuries, cities and governments have risen and fallen beyond the concent’s walls. Now, in celebration of the week-long, once-in-a-decade rite of Apert, the fraas and suurs prepare to venture beyond the concent’s gates — at the same time opening them wide to welcome the curious ‘extras’ in. During his first Apert as a fraa, Erasmas eagerly anticipates reconnecting with the landmarks and family he hasn’t seen since he was ‘collected.’ But before the week is out, both the existence he abandoned and the one he embraced will stand poised on the brink of cataclysmic change.”}
◊item{◊emph{◊amazon["B00NUMILJ2"]{Armor}} by John Steakley — 1984
“Felix is an Earth soldier, encased in special body armor designed to withstand Earth’s most implacable enemy-a bioengineered, insectoid alien horde. But Felix is also equipped with internal mechanisms that enable him, and his fellow soldiers, to survive battle situations that would destroy a man’s mind.”}
◊item{◊emph{◊amazon["B000FC1BNI"]{Oryx And Crake}} by Margaret Atwood — 2003
“Snowman (a man once known as Jimmy) sleeps in a tree and just might be the only human left on our devastated planet. He is not entirely alone, however, as he considers himself the shepherd of a group of experimental, human-like creatures called the Children of Crake. As he scavenges and tends to his insect bites, Snowman recalls in flashbacks how the world fell apart.”}
◊item{◊emph{◊amazon["B0064CPN7I"]{Fahrenheit 451}} by Ray Bradbury — 1953
“In Fahrenheit Ray Bradbury’s classic, frightening vision of the future, firemen don’t put out fires — they start them in order to burn books. Bradbury’s vividly painted society holds up the appearance of happiness as the highest goal — a place where trivial information is good, and knowledge and ideas are bad. Guy Montag is a book-burning fireman undergoing a crisis of faith. His wife spends all day with her television “family,” imploring Montag to work harder so that they can afford a fourth TV wall. Their dull, empty life sharply contrasts with that of his next-door neighbor Clarisse, a young girl thrilled by the ideas in books, and more interested in what she can see in the world around her than in the mindless chatter of the tube. When Clarisse disappears mysteriously, Montag is moved to make some changes, and starts hiding books in his home. Eventually, his wife turns him in, and he must answer the call to burn his secret cache of books. After fleeing to avoid arrest, Montag winds up joining an outlaw band of scholars who keep the contents of books in their heads, waiting for the time society will once again need the wisdom of literature.”}
◊item{◊emph{◊amazon["B000FBJAGO"]{A Fire Upon The Deep}} by Vernor Vinge — 1992
“Vinge presents a galaxy divided into Zones — regions where different physical constraints allow very different technological and mental possibilities. Earth remains in the ‘Slowness’ zone, where nothing can travel faster than light and minds are fairly limited. The action of the book is in the ‘Beyond,’ where translight travel and other marvels exist, and humans are one of many intelligent species. One human colony has been experimenting with ancient technology in order to find a path to the ‘Transcend,’ where intelligence and power are so great as to seem godlike. Instead they release the Blight, an evil power, from a billion-year captivity. As the Blight begins to spread, a few humans flee with a secret that might destroy it, but they are stranded in a primitive low-tech world barely in the Beyond. While the Blight destroys whole races and star systems, a team of two humans and two aliens races to rescue the others, pursued by the Blight’s agents and other enemies.”}
}
